version: '2'
services:
  mongo:
    container_name: mongo
    image: mongo    # 해당 service에서 사용할 image입니다.
    restart: always # container를 실행할 때 항상 이미 수행중이라면 재시작을 수행합니다.
    environment: # 환경변수를 정의합니다.
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Admin1234!
    volumes:
      - ./data:/data/db
    #      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports: # service port
      - "27017:27017"
